export const ADD_SENTIMENT_STARTED = 'ADD_SENTIMENT_STARTED'
export const ADD_SENTIMENT = 'ADD_SENTIMENT'
export const ADD_SENTIMENT_FAILURE = 'ADD_SENTIMENT_FAILURE'
export const GET_SENTIMENT = 'GET_SENTIMENT'